package review

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/fpt/klein-cli/internal/infra"
)

func TestIsGenerated(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{"protoc", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n", true},
		{"sqlc", "// Code generated by sqlc. DO NOT EDIT.\npackage db\n", true},
		{"after build tag", "//go:build linux\n\n// Code generated by stringer. DO NOT EDIT.\npackage x\n", true},
		{"license then marker", "// Copyright 2026\n// Code generated by mockgen. DO NOT EDIT.\npackage x\n", true},
		{"hand-written", "// Package foo does things.\npackage foo\n", false},
		{"marker after package ignored", "package foo\n\n// Code generated by x. DO NOT EDIT.\n", false},
		{"prose not marker", "// generated once by hand. DO NOT EDIT lightly.\npackage foo\n", false},
		{"empty", "", false},
		{"leading blank lines", "\n\n// Code generated by protoc. DO NOT EDIT.\npackage x\n", true},
	}
	for _, c := range cases {
		if got := IsGenerated(c.content); got != c.want {
			t.Errorf("%s: IsGenerated = %v, want %v", c.name, got, c.want)
		}
	}
}

func TestEnricherDropGenerated(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	write := func(name, content string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("gen.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\nvar X = 1\n")
	write("hand.go", "package main\n\nfunc main() {}\n")

	files := []FileDiff{
		{Path: "gen.go"},
		{Path: "hand.go"},
		{Path: "deleted.go", IsDeleted: true}, // unreadable → kept
	}
	e := NewEnricher(infra.NewOSFilesystemRepository(), dir, 5)
	kept, skipped := e.DropGenerated(context.Background(), files)

	if len(skipped) != 1 || skipped[0] != "gen.go" {
		t.Errorf("skipped = %v, want [gen.go]", skipped)
	}
	keptPaths := []string{}
	for _, f := range kept {
		keptPaths = append(keptPaths, f.Path)
	}
	if len(keptPaths) != 2 || keptPaths[0] != "hand.go" || keptPaths[1] != "deleted.go" {
		t.Errorf("kept = %v, want [hand.go deleted.go]", keptPaths)
	}
}
